# Generated by Django 5.1.7 on 2025-04-02 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, choices=[('webinaire', 'Webinaire'), ('atelier', 'Atelier'), ('talk', 'Talk')], max_length=100, null=True)),
                ('edition_du_Tour', models.CharField(blank=True, max_length=20, null=True)),
                ('nb_participants_max', models.IntegerField(default=0)),
                ('temps_de_participation', models.IntegerField(default=0)),
                ('date_de_debut', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes_animateur', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='programmes_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
