# Generated by Django 5.2 on 2025-05-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_nom_expertise_name_rename_nom_programme_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='date_de_creation',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='date_de_debut',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_de_creation',
            new_name='creation_date',
        ),
    ]
