# Generated by Django 5.2 on 2025-05-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_date_de_creation_programme_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='temps_de_participation',
            new_name='duration_hours',
        ),
    ]
