# Generated by Django 5.2 on 2025-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_temps_de_participation_programme_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='participants',
        ),
        migrations.AlterField(
            model_name='programme',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('termine', 'Terminé'), ('en_cours', 'En cours'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('en_cours', 'En cours'), ('annule', 'Annulé'), ('success', 'Succès')], default='registre', max_length=20),
        ),
    ]
