# Generated by Django 5.2 on 2025-06-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_programme_statut_alter_registration_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='statut',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='statut',
        ),
        migrations.AddField(
            model_name='programme',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('terminated', 'Terminated'), ('in_progress', 'In progress'), ('cancelled', 'Cancelled')], default='en_attente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('participant', 'programme', 'status')},
        ),
    ]
