# Generated by Django 5.2 on 2025-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_statut_registration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('animateur', 'Animateur'), ('admin', 'Admin')], max_length=20),
        ),
    ]
