# Generated by Django 5.2 on 2025-06-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('terminated', 'Terminated'), ('in_progress', 'In progress'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled'), ('success', 'Success')], default='inscrit', max_length=20),
        ),
    ]
