# Generated by Django 5.2 on 2025-05-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nom_user_name_remove_user_prenom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertise',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='nom',
            new_name='name',
        ),
    ]
