# Generated by Django 5.2 on 2025-05-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_registration_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='statut',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('terminated', 'Terminated'), ('in_progress', 'In progress'), ('cancelled', 'Cancelled')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='statut',
            field=models.CharField(choices=[('registered', 'Registered'), ('in_progress', 'In progress'), ('cancelled', 'Cancelled'), ('success', 'Success')], default='inscrit', max_length=20),
        ),
    ]
